name: Olaf
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  test-job:
    # The type of run ner that the job will run on
    runs-on: [ ubuntu-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: test-step
        # To use latest action, specify "release-master" instead of "v0.0.2"
        uses: satackey/action-js-inline@release-master
        with:
          package-manager: npm
          # Edit the following line to install packages required to run your script.
          required-packages: axios
          script: |
            const core = require('@actions/core');
            const axios = require('axios');

            
            const text = "this is a test text."
            const printText = () => console.log("@@@@@@@@@@@@@@@@", text);
            printText();
